FROM python:3.10-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip

# Install Python packages
COPY ./load-gen/requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

# Copy source code
COPY ./load-gen/ /load

# Set user
USER nobody

# Expose uvicorn port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "load.loadserver:app", "--host", "0.0.0.0", "--port", "8000"]
