services:
  loadserver:
    image: themonocledhamster/load-gen
    build: ./load-gen
    container_name: loadserver
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - "LOADSERVER_PORT=8000"
      - "LOADSERVER_HOST=0.0.0.0"
  model:
    image: themonocledhamster/counsel
    build: .
    container_name: counsel
    network_mode: "host"
